### ISSUE TITLE
False Postives Feedback

### ISSUE THREAD

**Issue by oempire** [wrender/modsecurity-whitelist-apps#1]
Hi, I have the following additions for wordpress and their associated files. 1 thing arent you meant to backslash the period in filename?

ill keep adding them as i come across, and try to start commenting - the comments seem to strip the filename out ><

`< DirectoryMatch '/wp-admin/admin-ajax\.php'>
	SecRuleRemoveById 981248
	SecRuleRemoveById 973339
	SecRuleRemoveById 981319
</DirectoryMatch>

< DirectoryMatch '/wp-admin/post\.php'>
	SecRuleRemoveById 981248
	SecRuleRemoveById 973339
	SecRuleRemoveById 960335
</DirectoryMatch>

< DirectoryMatch '/wp-admin/admin-ajax\.php'>
	SecRuleRemoveById 981248
	SecRuleRemoveById 973339
	SecRuleRemoveById 981319
</DirectoryMatch>

< DirectoryMatch '/wp-admin/async-upload\.php'>
	SecRuleRemoveById 960915
</DirectoryMatch>`

**Comment by wrender** [comment]
hey thanks @oempire . Are you able to write a pull request for it?  I am not sure if a backslash in a filename needs to be escaped. I don't see that anywhere in ModSecurity's documentation.

**Comment by wrender** [comment]
I think you need to define "LocationMatch" instead of "DirectoryMatch".  Also ModSecurity uses regex expressions to match the URLS.  I found the easiest way to learn this syntax was to use this tool online: http://regexr.com/

**Comment by oempire** [comment]
ahh ok, im just basing it on the tool i started with Config Server Mode security control. see screenshot of the interface https://i.imgur.com/fgnkeBo.png

**Comment by wrender** [comment]
I don't think any white-list's you create with that tool would be compatible with the white-lists I've put together.  This tool is completely un-related.

**Comment by oempire** [comment]
Hi apologies, no they dont show up in there but i was using that same syntax example for my custom rules (which ill just use yours now that i will submit further false positives)

**Comment by wrender** [comment]
great oempire. I look forward to merging in your wordpress false positives. it will really benefit everyone.
