### ISSUE TITLE
WHMCS Disable Rules

### ISSUE THREAD

**Issue by hrace009** [wrender/modsecurity-whitelist-apps#2]
Actualy this is not Issues, but only give information to the project owner.
Bellow i attached some WHMCS Rule Set at Admin area.
<pre><code>#WHMCS ADMIN AREA
<LocationMatch "/configgeneral.php">
  SecRuleRemoveById 973339 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 973340 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 950901 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 950911 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 950120 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 973343 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 973338 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 973322 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 973348 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 981257 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 981245 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 981240 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 981246 #WHMCS 6.X Problem at admin page
  SecRuleRemoveById 981243 #WHMCS 6.X Problem at admin page
</LocationMatch></code></pre>

**Comment by wrender** [comment]
Are you able to clarify what you mean by "Actually this is not issues?".  If you find a false positive I would ask that you create a pull request to incorporate the improvement.

**Comment by hrace009** [comment]
i have create a pull request, sorry i am not familiar with github

**Comment by wrender** [comment]
Thanks!!! I've merged it in.
